//! Session compaction: summary-style compression of the message history,
//! with a timeline separator inserted into the transcript.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use zhiyu_protocol::Message;

/// Timeline separator inserted after compaction, carrying the compaction
/// metadata the UI renders as a divider in the transcript.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CompactionSeparator {
    pub version: u32,
    pub kind: String, // "synthetic"
    pub r#type: String, // "context_compaction"
    pub status: String,
    pub trigger: String, // "manual" | "auto"
    pub pre_compact_token_count: u64,
    pub post_compact_token_count: u64,
    pub attempt: u32,
    pub max_attempts: u32,
}

impl CompactionSeparator {
    /// A manual compaction marker.
    pub fn manual(pre: u64, post: u64, attempt: u32, max: u32) -> Self {
        CompactionSeparator {
            version: 1,
            kind: "synthetic".into(),
            r#type: "context_compaction".into(),
            status: "ok".into(),
            trigger: "manual".into(),
            pre_compact_token_count: pre,
            post_compact_token_count: post,
            attempt,
            max_attempts: max,
        }
    }

    /// An auto-compaction marker.
    pub fn auto(pre: u64, post: u64, attempt: u32, max: u32) -> Self {
        let mut s = Self::manual(pre, post, attempt, max);
        s.trigger = "auto".into();
        s
    }

    /// The text rendered in the transcript.
    pub fn label(&self) -> String {
        format!(
            "上下文已压缩（{} → {} tokens，触发：{}）",
            self.pre_compact_token_count, self.post_compact_token_count, self.trigger
        )
    }
}

/// A compaction plan: which messages survive (recent ones kept verbatim), the
/// summary to insert, and the separator.
#[derive(Debug, Clone)]
pub struct CompactionPlan {
    pub summary: String,
    pub keep_from: usize,
    pub separator: CompactionSeparator,
}

/// Builds the compaction plan.
///
/// `messages` is the full transcript. The oldest messages (up to `keep_last`)
/// are summarized; the `keep_last` most recent are kept verbatim. The summary
/// text is generated by the caller (model call) and passed in via
/// `summary`.
pub fn plan_compaction(
    messages: &[Message],
    summary: String,
    keep_last: usize,
    trigger: &str,
    pre_tokens: u64,
    post_tokens: u64,
) -> CompactionPlan {
    let keep_from = messages.len().saturating_sub(keep_last);
    let separator = if trigger == "auto" {
        CompactionSeparator::auto(pre_tokens, post_tokens, 1, 1)
    } else {
        CompactionSeparator::manual(pre_tokens, post_tokens, 1, 1)
    };
    CompactionPlan { summary, keep_from, separator }
}

/// The messages to keep after compaction: summary (as a system message) +
/// the recent tail.
pub fn compacted_transcript(
    plan: &CompactionPlan,
    messages: &[Message],
    session_id: uuid::Uuid,
) -> Vec<Message> {
    let now: DateTime<Utc> = Utc::now();
    let mut out = Vec::new();
    // summary message
    out.push(Message {
        id: uuid::Uuid::new_v4(),
        session_id,
        role: zhiyu_protocol::Role::System,
        content: format!("【先前对话摘要】\n{}", plan.summary),
        reasoning: None,
        tool_name: None,
        cursor: 0,
        created_at: now,
    });
    // recent tail kept verbatim, cursors renumbered
    for (i, m) in messages.iter().skip(plan.keep_from).enumerate() {
        let mut kept = m.clone();
        kept.cursor = (i + 1) as u64;
        out.push(kept);
    }
    out
}

/// Decides whether auto-compaction should trigger: used ≥ threshold fraction
/// of the window.
pub fn should_auto_compact(used_tokens: u64, window: u64, ratio: f64) -> bool {
    window > 0 && used_tokens as f64 / window as f64 >= ratio
}

#[cfg(test)]
mod tests {
    use super::*;
    use zhiyu_protocol::Role;

    fn msgs(n: usize) -> Vec<Message> {
        (0..n)
            .map(|i| Message {
                id: uuid::Uuid::new_v4(),
                session_id: uuid::Uuid::new_v4(),
                role: if i % 2 == 0 { Role::User } else { Role::Assistant },
                content: format!("消息{i}"),
                reasoning: None,
                tool_name: None,
                cursor: i as u64,
                created_at: Utc::now(),
            })
            .collect()
    }

    #[test]
    fn manual_separator() {
        let s = CompactionSeparator::manual(10_000, 2_000, 1, 3);
        assert_eq!(s.trigger, "manual");
        assert_eq!(s.r#type, "context_compaction");
        assert_eq!(s.pre_compact_token_count, 10_000);
        assert_eq!(s.attempt, 1);
        assert_eq!(s.max_attempts, 3);
        assert!(s.label().contains("10_000".replace("_", " ").as_str()) || s.label().contains("10000"));
    }

    #[test]
    fn plan_keeps_recent_tail() {
        let msgs = msgs(10);
        let plan = plan_compaction(&msgs, "摘要内容".into(), 3, "manual", 100, 30);
        assert_eq!(plan.keep_from, 7);
        let kept = compacted_transcript(&plan, &msgs, msgs[0].session_id);
        // summary + 3 recent
        assert_eq!(kept.len(), 4);
        assert_eq!(kept[0].role, Role::System);
        assert!(kept[0].content.contains("摘要内容"));
        assert!(kept[3].content.contains("消息9"));
        // cursors renumbered
        assert_eq!(kept[3].cursor, 3);
    }

    #[test]
    fn auto_trigger_threshold() {
        assert!(should_auto_compact(85, 100, 0.85));
        assert!(!should_auto_compact(84, 100, 0.85));
        assert!(!should_auto_compact(0, 100, 0.85));
        assert!(!should_auto_compact(1000, 0, 0.85));
    }
}
